FROM node:22-alpine AS builder

ARG VITE_API_URL=https://api.yourdomain.com/api

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN VITE_API_URL=${VITE_API_URL} npm run build

FROM node:22-alpine

WORKDIR /app

RUN npm install -g serve && deluser node || true && addgroup -g 999 appuser && adduser -D -u 999 -G appuser appuser

COPY --from=builder --chown=appuser:appuser /app/dist /app/dist

USER appuser

EXPOSE 80

CMD ["serve", "-s", "dist", "-l", "80"]
