FROM node:22-alpine AS builder

ARG VITE_API_URL=https://api.yourdomain.com/api

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN VITE_API_URL=${VITE_API_URL} npm run build

FROM node:22-alpine

WORKDIR /app
RUN npm install -g serve

COPY --from=builder /app/dist /app/dist

EXPOSE 80

CMD ["serve", "-s", "dist", "-l", "80"]
