services:
  alloy:
    image: grafana/alloy:v1.6.1
    command: run --disable-reporting /etc/alloy/config.alloy
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GRAFANA_LOKI_URL=${GRAFANA_LOKI_URL:-}
      - GRAFANA_LOKI_USER=${GRAFANA_LOKI_USER:-}
      - GRAFANA_LOKI_API_KEY=${GRAFANA_LOKI_API_KEY:-}
      - GRAFANA_PROM_URL=${GRAFANA_PROM_URL:-}
      - GRAFANA_PROM_USER=${GRAFANA_PROM_USER:-}
      - GRAFANA_PROM_API_KEY=${GRAFANA_PROM_API_KEY:-}
    networks:
      - default
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
    name: ${DOKPLOY_NETWORK:-dokploy-network}
