services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: e_plant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5003:5432"

  backend:
    build: ./backend
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:5002"
    volumes:
      - ./backend:/app
    ports:
      - "5002:5002"
    depends_on:
      - db
      - mailhog
    environment:
      - POSTGRES_DB=e_plant_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5001:5001"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5002/api

volumes:
  postgres_data:
