# Generated by Django 5.2.11 on 2026-02-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="company_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="dic",
            field=models.CharField(blank=True, max_length=50, verbose_name="DIČ"),
        ),
        migrations.AddField(
            model_name="order",
            name="ico",
            field=models.CharField(blank=True, max_length=50, verbose_name="IČO"),
        ),
        migrations.AddField(
            model_name="order",
            name="is_company",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="street",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(blank=True),
        ),
    ]
