# Generated by Django 5.2.12 on 2026-04-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_dic_dph"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[("SK", "Slovensko"), ("CZ", "Česko")],
                default="SK",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_vat_payer",
            field=models.BooleanField(default=False, verbose_name="VAT payer"),
        ),
    ]
