# Generated by Django 5.2.12 on 2026-04-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_shippingrate_order_shipping_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[("SK", "Slovensko"), ("CZ", "Česko")],
                default="SK",
                max_length=2,
            ),
        ),
    ]
