# Generated by Django 5.2.12 on 2026-04-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_country_vat_payer"),
        ("orders", "0005_fix_batchlot_received_at_editable"),
    ]

    operations = []
