# Generated by Django 5.2.12 on 2026-04-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_add_country_to_address"),
        ("orders", "0005_fix_batchlot_received_at_editable"),
    ]

    operations = []
