# Generated by Django 5.2.12 on 2026-04-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_merge_20260405_1607"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shippingrate",
            unique_together={("country", "carrier")},
        ),
    ]
