# Generated by Django 5.2.13 on 2026-05-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_invoice_sent_status_flow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("bank_transfer", "Bankový prevod"), ("card", "Karta")],
                max_length=20,
            ),
        ),
    ]
