# Generated by Django 5.2.15 on 2026-06-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_orderitem_vat_rate_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
    ]
