# Generated by Django 5.2.5 on 2026-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_drop_category_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wildcardgroup",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
