# Generated by Django 5.2.14 on 2026-05-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_wildcardgroup_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupingsettings",
            name="visible_categories",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
