# Generated by Django 5.2.11 on 2026-03-01 15:00

from django.db import migrations, models


def normalize_globalsettings_singleton(apps, schema_editor):
    GlobalSettings = apps.get_model("users", "GlobalSettings")
    settings_rows = list(GlobalSettings.objects.order_by("pk"))

    if not settings_rows:
        GlobalSettings.objects.create(pk=1)
        return

    primary = settings_rows[0]

    if primary.pk != 1:
        GlobalSettings.objects.filter(pk=1).delete()
        primary.pk = 1
        primary.save()

    GlobalSettings.objects.exclude(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_customuser_username_alter_customuser_email"),
    ]

    operations = [
        migrations.RunPython(
            normalize_globalsettings_singleton, migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name="globalsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("pk", 1)), name="globalsettings_singleton_pk_1"
            ),
        ),
    ]
