# Generated by Django 5.2.12 on 2026-04-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[("SK", "Slovensko"), ("CZ", "Česko")],
                default="SK",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_vat_payer",
            field=models.BooleanField(default=False, verbose_name="VAT payer"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="vat_id",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="IČ DPH"),
        ),
    ]
