# Generated by Django 5.2.12 on 2026-04-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_customuser_vat_fields"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
