# Generated by Django 5.2.13 on 2026-05-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_globalsettings_company_vat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalsettings",
            name="warehouse_email",
            field=models.EmailField(default="warehouse@ebringer.sk", max_length=254),
        ),
    ]
