# Generated by Django 5.2.15 on 2026-06-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_customuser_annual_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalsettings",
            name="warehouse_email",
            field=models.EmailField(default="info@ebringer.sk", max_length=254),
        ),
    ]
